# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'cabunga-github'
    scannerMode: 'Other'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'cabunga-github'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'contexto'
    cliProjectName: 'contexto'
    cliSources: '.'
    extraProperties: |
      sonar.languages=java
      sonar.sources=src/main/java
      sonar.java.binaries=bin/*
      sonar.java.source=1.8
      sonar.sourceEncoding=UTF-8

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'